connect bands/Bands##123@localhost:1521/FREEPDB1

exec ords.enable_schema;
commit;


create or replace function f_get_object_id return varchar2 is
begin
    return ltrim(to_char(mod(floor(
                (to_date(to_char(sys_extract_utc(systimestamp), 'YYYY-MM-DD"T"HH24:MI:SS'),'YYYY-MM-DD"T"HH24:MI:SS') - to_date('1970-01-01','YYYY-MM-DD'))*24*60*60
            ),power(2,32)),'xxxxxxxx'),' ') || lower(substr(rawtohex(sys_guid()),32-5) || substr(rawtohex(sys_guid()),13,4) || substr(rawtohex(sys_guid()),7,6) );
end;
/

drop table if exists band_spinoffs;
drop table if exists associated_acts;
drop table if exists band_members;
drop table if exists artist_labels;
drop table if exists labels;
drop table if exists artist_genres;
drop table if exists genres;
drop table if exists artists;

create table artists (
  id               varchar2(30) not null ,
  name             varchar2(255) not null unique,
  link             varchar2(255),
  type             varchar2(20) not null,
  details          json,
  discovered       boolean default false,
  discover_time    timestamp default on null systimestamp,
  constraint artists_type_ck check (type in ('person','group_or_band')),
  constraint artists_pk primary key(id)
);


create table genres (
  id               varchar2(30) not null ,
  name             varchar2(255) not null unique,
  constraint genres_pk primary key(id)
);


create table artist_genres (
  id               integer generated by default on null as identity,
  genre_id         varchar2(30) not null ,
  artist_id        varchar2(30) not null ,
  constraint artist_genres_artists_fk foreign key (artist_id) references artists(id),
  constraint artist_genres_genres_fk foreign key (genre_id) references genres(id),
  constraint artist_genres_pk primary key(id)
);


create table labels (
  id               varchar2(30) not null ,
  name             varchar2(255) not null unique,
  constraint labels_pk primary key(id)
);

create table artist_labels (
  id               integer generated by default on null as identity,
  label_id         varchar2(30) not null ,
  artist_id        varchar2(30) not null ,
  constraint artist_labels_artists_fk foreign key (artist_id) references artists(id),
  constraint artist_labels_labels_fk foreign key (label_id) references labels(id),
  constraint artist_labels_pk primary key(id)
);


create table band_members (
  id               integer generated by default on null as identity,
  band_id          varchar2(30) not null,
  member_id        varchar2(30) not null,
  constraint band_members_band_fk foreign key (band_id) references artists(id),
  constraint band_members_member_fk foreign key (member_id) references artists(id),
  constraint band_members_pk primary key(id)
);

create table associated_acts (
  id               integer generated by default on null as identity,
  artist1_id         varchar2(30) not null,
  artist2_id         varchar2(30) not null,
  constraint associated_acts_artist1_fk foreign key (artist1_id) references artists(id),
  constraint associated_acts_artist2_fk foreign key (artist2_id) references artists(id),
  constraint associated_acts_pk primary key(id)
);


create table band_spinoffs (
  id               integer generated by default on null as identity,
  band_id          varchar2(30) not null,
  spinoff_id       varchar2(30) not null,
  constraint band_spinoffs_band_fk foreign key (band_id) references artists(id),
  constraint band_spinoffs_spinoff_fk foreign key (spinoff_id) references artists(id),
  constraint band_spinoffs_pk primary key(id)
);


